Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eShop.Entities.Entities;
using eShop.Infrastructure.Database;
using eShop.Infrastructure.Services;
using eShop.Presentation.ViewModels;
using FluentAssertions;

namespace eShop.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IEventService _eventService;
        private readonly ICategoryService _categoryService;

        public CategoryController(IEventService eventService, ICategoryService categoryService)
        {
            _eventService = eventService;
            _categoryService = categoryService;
        }

        // GET: Category
        public ActionResult Index()
        {
            var categories = _categoryService.AllCategories.OrderBy(g => g.CategoryId);
            return View(categories);
        }

        // GET: Category/Details/5
        [Route("/Create-a-category", Name = "Create a category")]
        public IActionResult Details(int? id)
        {
            var model = _categoryService.GetCategoryById(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category newCategory)
        {
            if (ModelState.IsValid)
            {
                _categoryService.CreateCategory(newCategory);
                return RedirectToAction(nameof(Details), new { id = _categoryService.AllCategories.Max(c => c.CategoryId) });
            }
            return View();
        }

        // GET: Categories/Edit/5
        public IActionResult Edit(int id)
        {
            var viewModel = new Category
            {
                CategoryId = id,
                CategoryName = _categoryService.GetCategoryById(id).CategoryName,
                Description = _categoryService.GetCategoryById(id).Description,
                Events = _categoryService.GetCategoryById(id).Events
            };
            if (viewModel == null)
            {
                return View("NotFound");
            }
            return View(viewModel);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Category newCategory)
        {
            if (ModelState.IsValid)
            {
                _categoryService.UpdateCategory(newCategory);
                return RedirectToAction(nameof(Details), new { id = newCategory.CategoryId });
            }
            return View();
        }

        // GET: Categories/Delete/5
        public IActionResult Delete(int? id)
        {
            var model = _categoryService.GetCategoryById(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, Category removedCategory)
        {
            if (ModelState.IsValid)
            {
                _categoryService.DeleteCategory(id);
            }
            return RedirectToAction("Index");
        }

        private bool CategoryExists(int id)
        {
            return _categoryService.AllCategories.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShop.Infrastructure.Services;
using eShop.Entities.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using eShop.Web.ViewModels;
using eShop.Presentation.ViewModels;
using eShop.Infrastructure.Configuration;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore.Internal;

namespace eShop.Web.Controllers
{
    public class EventController : Controller
    {
        // [TypeFilter(typeof(KillSwitchAuthorizationFilter))]
        private readonly IEventService _eventService;
        private readonly ICategoryService _categoryService;
        private readonly IScheduleService _scheduleService;
        private readonly ILocationService _locationService;
        private readonly ITeacherService _teacherService;
        private readonly ITicketService _ticketService;
        private readonly IFAQService _faqService;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly FeaturesConfiguration _featuresConfiguration;

        [BindProperty(SupportsGet = true)]
        public string SearchedEventBar { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchedEvent { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchedCategory { get; set; }

        public EventController
            (
            IEventService eventService,
            ICategoryService categoryService,
            IScheduleService scheduleService,
            ILocationService locationService,
            ITeacherService teachersService,
            ITicketService ticketService,
            IFAQService faqService,
            ShoppingCartService shoppingCartService,
            IOptions<FeaturesConfiguration> options
            )
        {
            _scheduleService = scheduleService;
            _eventService = eventService;
            _categoryService = categoryService;
            _locationService = locationService;
            _teacherService = teachersService;
            _ticketService = ticketService;
            _faqService = faqService;
            _shoppingCartService = shoppingCartService;
            _featuresConfiguration = options.Value;
        }

        // GET: Event
        public ActionResult Index(string category)
        {
            IEnumerable<Event> events;

            List<List<Day>> daysList = new List<List<Day>>();
            var eventsList = _eventService.AllEvents();
            foreach (var e in eventsList)
            {
                var days = _scheduleService.GetEventDays(e.EventId, false);
                daysList.Add(days); 
            }
            var times = _scheduleService.GetAllEventsTimesList();

            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                events = _eventService.AllEvents(SearchedEvent, SearchedCategory).OrderBy(e => e.EventId);

                if (SearchedEvent != null)
                {
                    currentCategory = SearchedCategory;
                }
                else
                {
                    currentCategory = "All events";
                }
            }
            else
            {
                events = _eventService.AllEvents(SearchedEvent, SearchedCategory).Where(p => p.Category.CategoryName == category)
                    .OrderBy(e => e.EventId);
                currentCategory = _categoryService.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new EventViewModel
            {
                Events = events,
                DaysList = daysList,
                CurrentCategory = currentCategory,
                SearchedEvent = SearchedEvent,
                SearchedCategory = SearchedCategory,
                NotFoundSearchedEventMessage = "No events were found that matched your criteria",
                Categories = _categoryService.AllCategories.ToList()
            });
        }

        // GET: Event/Details/5
        public IActionResult Details(int id)
        {
            var eventDetails = _eventService.GetEventById(id);
            var days = _scheduleService.GetEventDays(id, false);
            var times = _scheduleService.GetEventTimes(id, false);
            var locations = _locationService.GetLocationById(id);
            var teachers = _teacherService.GetTeachersById(id);
            var selectedAmount = _shoppingCartService.GetShoppingCartItemAmount(id);
            var tickets = _ticketService.GetTicketById(id);
            var faqs = _faqService.GetFAQById(id);
            var isBoughtTicket = _shoppingCartService.GetShoppingCartItems(id).Any();
            var shoppingCartItems = _shoppingCartService.GetShoppingCartItems(id);


            if (selectedAmount == 0)
            {
                selectedAmount = 1;
            }

            if (eventDetails == null)
            {
                return View("NotFound");
            }

            return View(new EventViewModel
            {
                ShoppingCartItemTotalSEK = _shoppingCartService.GetShoppingCartItemTotalSEK(id),
                ShoppingCartItemTotalEUR = _shoppingCartService.GetShoppingCartItemTotalEUR(id),
                SelectedAmount = selectedAmount,
                Event = eventDetails,
                Days = days,
                Times = times,
                Locations = locations,
                FAQs = faqs,
                Teachers = teachers,
                Tickets = tickets,
                IsBoughtTicket = isBoughtTicket,
                NotFoundSchedule = "The event does not have a schedule yet!"
            });
        }


        // GET: Event/CreateStepOne
        // [Route("/Event/Create-Step-One")]
        // [HttpGet]
        public IActionResult CreateStepOne()
        {
            var viewModel = new EventViewModel
            {
                Categories = _categoryService.AllCategories.ToList()
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepOne
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepOne(EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _eventService.CreateEvent(newEvent);

                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepTwo), new { id = eventId, isNewEvent = true });
            }
            return View();
        }

        // GET: Event/CreateStepTwo
        // [Route("/Event/Create-Step-Two")]
        // [HttpGet]
        public IActionResult CreateStepTwo(int id, bool isNewEvent)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Days = _scheduleService.GetEventDays(id, isNewEvent),
                Times = _scheduleService.GetEventTimes(id, isNewEvent)
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepTwo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepTwo(EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _scheduleService.CreateSchedule(newEvent);
                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepTwo), new { id = eventId });
            }
            return View();
        }

        // GET: Event/CreateStepThree
        //[Route("/Event/Create-Step-Three")]
        //[HttpGet]
        public IActionResult CreateStepThree(int id)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Event = _eventService.GetEventById(id),
                Tickets = _ticketService.GetTicketById(id)
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepThree
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepThree(int id, EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _ticketService.CreateTicket(_eventService.AllEvents().Max(e => e.EventId), newEvent);
                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepFour), new { id = eventId });                
            }
            return View();
        }

        // GET: Event/CreateStepFour
        //[Route("/Event/Create-Step-Four")]
        //[HttpGet]
        public IActionResult CreateStepFour(int id)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Event = _eventService.GetEventById(id),
                Teachers = _teacherService.GetTeachersById(id)
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepFour
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepFour(int id, EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _teacherService.CreateTeacher(_eventService.AllEvents().Max(e => e.EventId), newEvent);
                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepFive), new { id = eventId });
            }
            return View();
        }

        // GET: Event/CreateStepFive
        //[Route("/Event/Create-Step-Five")]
        //[HttpGet]
        public IActionResult CreateStepFive(int id)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Event = _eventService.GetEventById(id),
                Locations = _locationService.GetLocationById(id),
                FAQs = _faqService.GetFAQById(id)

Views/Shared/Outage.cshtml
@{
    ViewData["Title"] = "Outage";
}

<div class="text-center">
    <h1 class="display-4">Blocked Page</h1>
    <a>The website is under construction!</a>
</div>

Views/Shared/_CategoryCard.cshtml
@model eShop.Entities.Entities.Category


<div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
    <div class="category-card">
        <div class="card m-0 my-3 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal text-center">
                    <a asp-controller="Event" asp-action="Index" asp-route-category="@Model.CategoryName">
                        @Model.CategoryName
                    </a>
                </h4>
            </div>
            <div class="img-fluid">
                <a asp-controller="Event" asp-action="Index" asp-route-category="@Model.CategoryName">
                    <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSGwZOMqbstzhzyFc090olrusblDgJttOqDheRRHktC3JUTOP57&usqp=CAU" alt="@Model.CategoryName">
                </a>
            </div>
                <div class="card-body">
                    <h4 class="card-title">@Model.CategoryName</h4>
                    <p class="card-subtitle mb-2 text-muted">@Model.Description.</p>
                    <a asp-controller="Event"
                       asp-action="Index"
                       asp-route-category="@Model.CategoryName"
                       role="button" class="btn btn-block btn-danger text-nowrap">
                        See the events
                    </a>
                </div>
                <div class="d-inline-block">
                    <a asp-controller="Category" asp-action="Edit" asp-route-id="@Model.CategoryId">Edit</a> |
                    <a asp-controller="Category" asp-action="Delete" asp-route-id="@Model.CategoryId">Delete</a>
                </div>
            </div>
        </div>
</div>

Views/Shared/_CreateFAQ.cshtml
@model eShop.Presentation.ViewModels.EventViewModel


<div class="form-group col">
    <label asp-for="FAQ.Question" class="control-label"></label>
    <input asp-for="FAQ.Question" class="form-control" />
    <span asp-validation-for="FAQ.Question" class="text-danger"></span>
    <div class="invalid-tooltip">
        Please provide a question.
    </div>
</div>

<div class="form-group col">
    <label asp-for="FAQ.Answer" class="control-label"></label>
    <textarea asp-for="FAQ.Answer" class="form-control"></textarea>
    <span asp-validation-for="FAQ.Answer" class="text-danger"></span>
</div>
<div class="invalid-tooltip">
    Please provide an answer.
</div>

Views/Shared/_CreateLocation.cshtml
@model eShop.Presentation.ViewModels.EventViewModel

    <div class="form-row">
        <div class="form-group col-md-8">
            <label asp-for="Location.Street" class="control-label"></label>
            <input asp-for="Location.Street" class="form-control" />
            <span asp-validation-for="Location.Street" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide a street.
            </div>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Location.StreetNumber" class="control-label"></label>
            <input asp-for="Location.StreetNumber" class="form-control" />
            <span asp-validation-for="Location.StreetNumber" class="text-danger"></span>
        </div>
        <div class="invalid-tooltip">
            Please provide a street number.
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Location.City" class="control-label"></label>
            <input asp-for="Location.City" class="form-control" />
            <span asp-validation-for="Location.City" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide a city.
            </div>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Location.State" class="control-label"></label>
            <input asp-for="Location.State" class="form-control" />
            <span asp-validation-for="Location.State" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide a state.
            </div>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="Location.ZipCode" class="control-label"></label>
            <input asp-for="Location.ZipCode" class="form-control" />
            <span asp-validation-for="Location.ZipCode" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide a zip code.
            </div>
        </div>
    </div>

Views/Shared/_CreateSchedule.cshtml
@model eShop.Presentation.ViewModels.EventViewModel

    <div class="form-row">
        <div class="col-md-4 pt-3">
            <label asp-for="Day.Date" class="control-label"></label>
            <input class="form-control" type="date" asp-for="Day.Date">
            <span asp-validation-for="Day.Date" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide a date.
            </div>
        </div>

        <div class="col-md-4 pt-3">
            <label asp-for="Time.TimeStart" class="control-label"></label>
            <input asp-for="Time.TimeStart" type="time" class="form-control" />
            <span asp-validation-for="Time.TimeStart" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide a start time.
            </div>
        </div>

        <div class="col-md-4 pt-3">
            <label asp-for="Time.TimeEnd" class="control-label"></label>
            <input asp-for="Time.TimeEnd" type="time" class="form-control" />
            <span asp-validation-for="Time.TimeEnd" class="text-danger"></span>
            <div class="invalid-tooltip">
                Please provide an end time.
            </div>
        </div>
    </div>

Views/Shared/_CreateTeacher.cshtml
@model eShop.Presentation.ViewModels.EventViewModel
<div class="form-row">
    <div class="col pt-3">
        <label asp-for="Teacher.TeacherName" class="control-label"></label>
        <input asp-for="Teacher.TeacherName" class="form-control" />
        <span asp-validation-for="Teacher.TeacherName" class="text-danger"></span>
        <div class="invalid-tooltip">
            Please provide a teacher name.
        </div>
    </div>
</div>
<div class="form-row">
    <div class="col pt-3">
        <label asp-for="Teacher.TeacherDescription" class="control-label"></label>
        <textarea asp-for="Teacher.TeacherDescription" class="form-control"></textarea>
        <span asp-validation-for="Teacher.TeacherDescription" class="text-danger"></span>
        <div class="invalid-tooltip">
            Please provide a description.
        </div>
    </div>
</div>

Views/Shared/_CreateTicket.cshtml
@model eShop.Presentation.ViewModels.EventViewModel
<div class="form-row">
    <div class="col pt-3">
        <label asp-for="Ticket.TicketName" class="control-label"></label>
        <input asp-for="Ticket.TicketName" class="form-control" />
        <span asp-validation-for="Ticket.TicketName" class="text-danger"></span>
        <div class="invalid-tooltip">
            Please provide a ticket name.
        </div>
    </div>
</div>
<div class="form-row">
    <div class="col-md-6 pt-3">
        <label asp-for="Ticket.TicketPrice" class="control-label"></label>
        <input asp-for="Ticket.TicketPrice" class="form-control" />
        <span asp-validation-for="Ticket.TicketPrice" class="text-danger"></span>
        <div class="invalid-tooltip">
            Please provide a price.
        </div>
    </div>
    <div class="col-md-6 pt-3">
        <label asp-for="Ticket.TotalAvailableTicket" class="control-label"></label>
        <input asp-for="Ticket.TotalAvailableTicket" class="form-control"  />
        <span asp-validation-for="Ticket.TotalAvailableTicket" class="text-danger"></span>
        <div class="invalid-tooltip">
            Please provide a number of tickets.
        </div>
    </div>
</div>
<div class="form-row">
    <div class="col pt-3">
        <label asp-for="Ticket.Description" class="control-label"></label>
        <textarea asp-for="Ticket.Description" class="form-control" row="3" ></textarea>
        <span asp-validation-for="Ticket.Description" class="text-danger"></span>
        <div class="invalid-tooltip">
            Please provide a description.
        </div>
    </div>
</div>

Views/Shared/_EventCard.cshtml
@model eShop.Presentation.ViewModels.EventViewModel

@{
    int i = 0;
    @foreach (var item in Model.Events)
    {
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
            <div class="event-card">
                <div class="card w-auto m-0 my-3 shadow-sm">
                    <div class="img-fluid">
                        <a asp-controller="Event" asp-action="Details" asp-route-id="@item.EventId">
                            <img class="card-img-top" src="@item.ImageUrl" alt="@item.Name">
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> <a asp-controller="Event" asp-action="Details" asp-route-id="@item.EventId" class="text-decoration-none">@item.Name</a></h5>
                        <h6 class="card-subtitle mb-2 text-muted">@item.ShortDescription.</h6>
                        <div class="buy d-flex justify-content-between align-items-center">
                            <div class="text-dark">
                                <div class="mt-4 text-nowrap font-weight-bold">
                                    @{                                        
                                        if (@Model.DaysList[i].Count() > 1)
                                        {
                                            <div class="font-weight-normal">From</div> @Model.DaysList[i][0].Date.ToString("MMMM dd, yyyy")
                                        }
                                        else
                                        {
                                            @Model.DaysList[i][0].Date.ToString("MMMM dd, yyyy")
                                        }
                                    }
                                </div>
                            </div>

                            <a asp-controller="Event"
                               asp-action="Details"
                               asp-route-id="@item.EventId"
                               role="button" class="btn btn-danger mt-3 text-nowrap">
                                Read more
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        i++;
    }
}

Views/Shared/_EventLocations.cshtml
@model eShop.Presentation.ViewModels.EventViewModel


<div class="card-group">
    @{
        for (int i = 0; i < @Model.Locations.ToList().Count(); i++)
        {
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                <div class="event-card">
                    <div class="card w-auto m-0 my-3 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title">@Model.Locations.ToList()[i].Street @Model.Locations.ToList()[i].StreetNumber</h5>
                            @*<h6 class="card-subtitle mb-2 text-muted"> @Model.Locations.ToList()[i].TicketPrice @Model.Event.Currency </h6>*@
                            <address>
                                @Model.Locations.ToList()[i].Street @Model.Locations.ToList()[i].StreetNumber
                                <br>
                                @Model.Locations.ToList()[i].ZipCode @Model.Locations.ToList()[i].City
                                <br>
                                @Model.Locations.ToList()[i].State
                            </address>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

Views/Shared/_EventTeachers.cshtml
@model eShop.Presentation.ViewModels.EventViewModel


<div class="card-group">
    @{
        for (int i = 0; i < @Model.Teachers.ToList().Count(); i++)
        {
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                <div class="event-card">
                    <div class="card w-auto m-0 my-3 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title">  @Model.Teachers.ToList()[i].TeacherName</h5>
                            @*<h6 class="card-subtitle mb-2 text-muted"> @Model.Tickets.ToList()[i].TicketPrice @Model.Event.Currency </h6>*@
                            <div class="buy d-flex justify-content-between align-items-center">
                                @Model.Teachers.ToList()[i].TeacherDescription
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

Views/Shared/_EventsFilter.cshtml
@model eShop.Presentation.ViewModels.EventViewModel

<form asp-controller="Event" asp-action="Index" method="get" role="form">

    <div class="container-fluid bg-transparent">
        <div class="form-row m-3 align-items-center justify-content-center">

            <div class="col-md-3 pt-3">
                <select asp-for="SearchedCategory" class="form-control" asp-items="@(new SelectList(Model.Categories, "CategoryName", "CategoryName"))">
                    <option value="">Select a category</option>
                </select>
            </div>

            <div class="col-md-3 pt-3">
                <select id="inputState" class="form-control">
                    <option selected>Type of event</option>
                    <option>Classes</option>
                    <option>Workshops</option>
                    <option>Parties</option>
                    <option>Festivals</option>
                </select>
            </div>

            <div class="col-md-3 pt-3">
                <input class="form-control" type="text" asp-for="SearchedEvent" placeholder="Search">
            </div>

            <div class="col-md-3 pt-3">
                <input type="submit" class="btn btn-danger text-nowrap btn-block" value="Search" />
            </div>

        </div>
    </div>
</form>