ViewModels/ShoppingCartViewModel.cs
using eShop.Infrastructure.Services;
using eShop.Entities.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShop.Infrastructure;
using System.ComponentModel.DataAnnotations;

namespace eShop.Web.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCartService ShoppingCartService { get; set; }
        public decimal ShoppingCartTotalSEK { get; set; }        
        public decimal ShoppingCartTotalEUR { get; set; }

        public IList<Ticket> Tickets { get; set; }


        [Required]
        [UIHint("Number")]
        [Display(Name = "Amount of classes", Prompt = "Enter an number")]
        public int SelectedAmount { get; set; }

        [Required]
        [UIHint("Number")]
        [Display(Name = "Type of ticket", Prompt = "Choose a ticket")]
        public int SelectedTicketId { get; set; }
    }
}

Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShop.Infrastructure.Services;
using eShop.Entities.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using eShop.Web.ViewModels;
using eShop.Presentation.ViewModels;
using eShop.Infrastructure.Configuration;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore.Internal;

namespace eShop.Web.Controllers
{
    public class EventController : Controller
    {
        // [TypeFilter(typeof(KillSwitchAuthorizationFilter))]
        private readonly IEventService _eventService;
        private readonly ICategoryService _categoryService;
        private readonly IScheduleService _scheduleService;
        private readonly ILocationService _locationService;
        private readonly ITeacherService _teacherService;
        private readonly ITicketService _ticketService;
        private readonly IFAQService _faqService;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly FeaturesConfiguration _featuresConfiguration;

        [BindProperty(SupportsGet = true)]
        public string SearchedEventBar { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchedEvent { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchedCategory { get; set; }

        public EventController
            (
            IEventService eventService,
            ICategoryService categoryService,
            IScheduleService scheduleService,
            ILocationService locationService,
            ITeacherService teachersService,
            ITicketService ticketService,
            IFAQService faqService,
            ShoppingCartService shoppingCartService,
            IOptions<FeaturesConfiguration> options
            )
        {
            _scheduleService = scheduleService;
            _eventService = eventService;
            _categoryService = categoryService;
            _locationService = locationService;
            _teacherService = teachersService;
            _ticketService = ticketService;
            _faqService = faqService;
            _shoppingCartService = shoppingCartService;
            _featuresConfiguration = options.Value;
        }

        // GET: Event
        public ActionResult Index(string category)
        {
            IEnumerable<Event> events;

            List<List<Day>> daysList = new List<List<Day>>();
            var eventsList = _eventService.AllEvents();
            foreach (var e in eventsList)
            {
                var days = _scheduleService.GetEventDays(e.EventId, false);
                daysList.Add(days); 
            }
            var times = _scheduleService.GetAllEventsTimesList();

            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                events = _eventService.AllEvents(SearchedEvent, SearchedCategory).OrderBy(e => e.EventId);

                if (SearchedEvent != null)
                {
                    currentCategory = SearchedCategory;
                }
                else
                {
                    currentCategory = "All events";
                }
            }
            else
            {
                events = _eventService.AllEvents(SearchedEvent, SearchedCategory).Where(p => p.Category.CategoryName == category)
                    .OrderBy(e => e.EventId);
                currentCategory = _categoryService.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new EventViewModel
            {
                Events = events,
                DaysList = daysList,
                CurrentCategory = currentCategory,
                SearchedEvent = SearchedEvent,
                SearchedCategory = SearchedCategory,
                NotFoundSearchedEventMessage = "No events were found that matched your criteria",
                Categories = _categoryService.AllCategories.ToList()
            });
        }

        // GET: Event/Details/5
        public IActionResult Details(int id)
        {
            var eventDetails = _eventService.GetEventById(id);
            var days = _scheduleService.GetEventDays(id, false);
            var times = _scheduleService.GetEventTimes(id, false);
            var locations = _locationService.GetLocationById(id);
            var teachers = _teacherService.GetTeachersById(id);
            var selectedAmount = _shoppingCartService.GetShoppingCartItemAmount(id);
            var tickets = _ticketService.GetTicketById(id);
            var faqs = _faqService.GetFAQById(id);
            var isBoughtTicket = _shoppingCartService.GetShoppingCartItems(id).Any();
            var shoppingCartItems = _shoppingCartService.GetShoppingCartItems(id);


            if (selectedAmount == 0)
            {
                selectedAmount = 1;
            }

            if (eventDetails == null)
            {
                return View("NotFound");
            }

            return View(new EventViewModel
            {
                ShoppingCartItemTotalSEK = _shoppingCartService.GetShoppingCartItemTotalSEK(id),
                ShoppingCartItemTotalEUR = _shoppingCartService.GetShoppingCartItemTotalEUR(id),
                SelectedAmount = selectedAmount,
                Event = eventDetails,
                Days = days,
                Times = times,
                Locations = locations,
                FAQs = faqs,
                Teachers = teachers,
                Tickets = tickets,
                IsBoughtTicket = isBoughtTicket,
                NotFoundSchedule = "The event does not have a schedule yet!"
            });
        }


        // GET: Event/CreateStepOne
        // [Route("/Event/Create-Step-One")]
        // [HttpGet]
        public IActionResult CreateStepOne()
        {
            var viewModel = new EventViewModel
            {
                Categories = _categoryService.AllCategories.ToList()
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepOne
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepOne(EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _eventService.CreateEvent(newEvent);

                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepTwo), new { id = eventId, isNewEvent = true });
            }
            return View();
        }

        // GET: Event/CreateStepTwo
        // [Route("/Event/Create-Step-Two")]
        // [HttpGet]
        public IActionResult CreateStepTwo(int id, bool isNewEvent)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Days = _scheduleService.GetEventDays(id, isNewEvent),
                Times = _scheduleService.GetEventTimes(id, isNewEvent)
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepTwo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepTwo(EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _scheduleService.CreateSchedule(newEvent);
                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepTwo), new { id = eventId });
            }
            return View();
        }

        // GET: Event/CreateStepThree
        //[Route("/Event/Create-Step-Three")]
        //[HttpGet]
        public IActionResult CreateStepThree(int id)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Event = _eventService.GetEventById(id),
                Tickets = _ticketService.GetTicketById(id)
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepThree
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepThree(int id, EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _ticketService.CreateTicket(_eventService.AllEvents().Max(e => e.EventId), newEvent);
                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepFour), new { id = eventId });                
            }
            return View();
        }

        // GET: Event/CreateStepFour
        //[Route("/Event/Create-Step-Four")]
        //[HttpGet]
        public IActionResult CreateStepFour(int id)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Event = _eventService.GetEventById(id),
                Teachers = _teacherService.GetTeachersById(id)
            };
            return View(viewModel);
        }

        // POST: Event/CreateStepFour
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateStepFour(int id, EventViewModel newEvent)
        {
            if (ModelState.IsValid)
            {
                _teacherService.CreateTeacher(_eventService.AllEvents().Max(e => e.EventId), newEvent);
                var eventId = _eventService.AllEvents().Max(e => e.EventId);
                return RedirectToAction(nameof(CreateStepFive), new { id = eventId });
            }
            return View();
        }

        // GET: Event/CreateStepFive
        //[Route("/Event/Create-Step-Five")]
        //[HttpGet]
        public IActionResult CreateStepFive(int id)
        {
            var viewModel = new EventViewModel
            {
                EventId = id,
                Event = _eventService.GetEventById(id),
                Locations = _locationService.GetLocationById(id),
                FAQs = _faqService.GetFAQById(id)

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShop.Infrastructure;
using eShop.Infrastructure.Services;
using eShop.Entities.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Options;
using eShop.Infrastructure.Configuration;
using Microsoft.Extensions.Options;
using eShop.Infrastructure.Rule;
using eShop.Presentation.ViewModels;

namespace eShop.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly FeaturesConfiguration _featuresConfiguration;      
        private IRuleProcessor _ruleProcessor;

        public OrderController
            (
            IOrderService orderService, 
            ShoppingCartService shoppingCartService, 
            IOptions<FeaturesConfiguration> options,          
            IRuleProcessor ruleProcessor
            )
        {
            _orderService = orderService;
            _shoppingCartService = shoppingCartService;
            _featuresConfiguration = options.Value;          
            _ruleProcessor = ruleProcessor;
        }
        // GET: /<controller>/
        public IActionResult Checkout()
        {
            var (passedRules, errors) = _ruleProcessor.PassesAllRules();          
            if (passedRules)
            {
                return View();
            }
            else
            {
                return View("_BlockedPage");
            }
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCartService.GetShoppingCartItems();
            _shoppingCartService.ShoppingCartItems = items;

            if (_shoppingCartService.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty.");
            }

            if (ModelState.IsValid)
            {
                _orderService.CreateOrder(order);
                _shoppingCartService.ClearCart();
                return RedirectToAction("CheckoutComplete");
            }
            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order!";
            return View();
        }
    }
}

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eShop.Infrastructure;
using eShop.Web.ViewModels;
using eShop.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using eShop.Infrastructure.Configuration;
using Microsoft.Extensions.Options;
using eShop.Entities.Entities;
using eShop.Presentation.ViewModels;

namespace eShop.Web.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ITicketService _ticketService;
        private readonly IEventService _eventService;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly FeaturesConfiguration _featuresConfiguration;


        [BindProperty(SupportsGet = true)]
        public int SelectedAmount { get; set; }

        [BindProperty(SupportsGet = true)]
        public int SelectedTicketId { get; set; }

        public ShoppingCartController
        (
            ITicketService ticketService,
            IEventService eventService,
            ShoppingCartService shoppingCartService,
            IOptions<FeaturesConfiguration> options
        )
        {
            _ticketService = ticketService;
            _eventService = eventService;
            _shoppingCartService = shoppingCartService;
            _featuresConfiguration = options.Value;
        }
        public IActionResult Index()
        {
            if (_featuresConfiguration.EnableOrder)
            {
                var items = _shoppingCartService.GetShoppingCartItems();
                _shoppingCartService.ShoppingCartItems = items;

                var shoppingCartViewModel = new ShoppingCartViewModel
                {
                    Tickets = _shoppingCartService.GetTickets(),
                    ShoppingCartService = _shoppingCartService,
                    ShoppingCartTotalSEK = _shoppingCartService.GetShoppingCartTotalSEK(),
                    ShoppingCartTotalEUR = _shoppingCartService.GetShoppingCartTotalEUR(),
                };

                return View(shoppingCartViewModel);
            }
            else
            {
                return View("_BlockedPage");
            }
        }

        public RedirectToActionResult AddToShoppingCart(int eventId, int ticketId, bool isDetailesPage)
        {
            if (_featuresConfiguration.EnableOrder)
            {
                var selectedEvent = _eventService.AllEvents().FirstOrDefault(e => e.EventId == eventId);
                if (SelectedTicketId == 0)
                {
                    SelectedTicketId = ticketId;
                }
                var SelectedTicket = _ticketService.AllTickets.FirstOrDefault(t => t.TicketId == SelectedTicketId);

                if (selectedEvent != null)
                {
                    _shoppingCartService.AddToCart(selectedEvent, SelectedTicket, SelectedAmount, isDetailesPage);
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public RedirectToActionResult RemoveFromShoppingCart(int eventId, int ticketId)
        {
            if (eventId != 0 || ticketId != 0)
            {
                _shoppingCartService.RemoveFromCart(eventId, ticketId);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/ShoppingCart/Index.cshtml
@model eShop.Web.ViewModels.ShoppingCartViewModel

<h2>Your shopping cart</h2>
<h4>Here are the events in your shopping cart.</h4>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Event</th>
            <th scope="col" class="px-0">
                <div class="d-flex justify-content-around align-items-center">
                    <div class="col text-center">Ticket</div>
                    <div class="col-8 text-center">Qty</div>
                </div>
            </th>
            <th scope="col" class="text-center">Price</th>
            <th scope="col" class="text-center">Total</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 0;
            @foreach (var line in Model.ShoppingCartService.ShoppingCartItems)
            {
                <tr>
                    <td class="w-25 pt-3 pb-1">
                        <a asp-controller="Event" asp-action="Details" asp-route-id="@line.Event.EventId"><h5 class="text-decoration-none text-nowrap">@line.Event.Name</h5></a>
                    </td>
                    <td class="pt-3 pb-1">
                        <form asp-controller="ShoppingCart"
                              asp-action="AddToShoppingCart"
                              asp-route-eventId="@line.Event.EventId"
                              asp-route-ticketId="@line.Ticket.TicketId"
                              asp-route-isDetailesPage="@false"
                              method="post" role="form">

                            <div class="d-flex justify-content-around align-items-center">

                                <div class="d-flex justify-content-center">
                                    <div class="form-group col">
                                        @line.Ticket.TicketName

                                        @*<div class="input-group">
                                                <select asp-for="@Model.SelectedTicketId" class="custom-select form-control text-center w-auto" asp-items="@(new SelectList(Model.Tickets, "TicketId", "TicketName"))">
                                                    <option value="@line.Ticket.TicketId">@line.Ticket.TicketName</option>
                                                </select>

                                                <div class="input-group-append">
                                                    <button class="btn btn-sm btn-outline-secondary" type="submit">Edit</button>
                                                </div>
                                            </div>*@
                                    </div>
                                </div>

                                <div class="d-flex justify-content-center">
                                    <div class="form-group col-8">
                                            <div class="input-group">
                                                <input class="form-control text-center" type="number" asp-for="@Model.SelectedAmount" value="@line.Amount">

                                                <div class="input-group-append">
                                                    <button class="btn btn-sm btn-outline-secondary" type="submit">Edit</button>
                                                </div>
                                            </div>
                                        </div>
                                </div>

                            </div>
                        </form>
                    </td>
                    <td class="pt-3 pb-1 text-center">@line.Ticket.TicketPrice  @line.Event.Currency</td>
                    <td class="pt-3 pb-1 text-center">@(line.Amount * line.Ticket.TicketPrice) @(line.Event.Currency)</td>
                    <td class="pt-3 pb-1 d-flex justify-content-center">
                        <a asp-controller="ShoppingCart"
                           asp-action="RemoveFromShoppingCart"
                           asp-route-eventId="@line.Event.EventId"
                           asp-route-ticketId="@line.Ticket.TicketId"
                           class="btn btn-danger btn-sm">
                            <i class="fa fa-times"></i>
                        </a>
                    </td>
                </tr>
            }
            i++;
        }
    </tbody>
    <tfoot>
        @if (@Model.ShoppingCartTotalSEK != 0)
        {
            <tr>
                <td colspan="3"><h5 class="text-right font-weight-bold">Total:</h5></td>
                <td colspan="2">
                    <h5 class="price text-success text-center">@String.Format("{0:0.00}", @Model.ShoppingCartTotalSEK) SEK</h5>
                </td>
            </tr>
        }
        @if (@Model.ShoppingCartTotalEUR != 0)
        {
            <tr>
                <td colspan="3"><h5 class="text-right font-weight-bold">Total:</h5></td>
                <td colspan="2">
                    <h5 class="price text-success text-center">@String.Format("{0:0.00}", Model.ShoppingCartTotalEUR) EUR</h5>
                </td>
            </tr>
        }
    </tfoot>
</table>



@{
    if (Model.ShoppingCartService.ShoppingCartItems.Count() != 0)
    {
        <div class="d-flex justify-content-end">
            <a class="btn btn-lg btn-danger w-25 text-center text-nowrap" asp-controller="Order" asp-action="Checkout">Check out now!</a>
        </div>
    }
    else
    {
        <div class="d-flex justify-content-end">
            <a class="btn btn-lg btn-danger w-25 disabled text-center text-nowrap" asp-controller="Order" asp-action="Checkout">Check out now!</a>
        </div>
    }
}

<div>
    <a asp-controller="Home" asp-action="Index">Go to Homepage</a>
</div>